services:
  - type: web
    name: diabetic-marketplace-api
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: MONGODB_URI
        sync: false # Нужно добавить вручную
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: VK_APP_ID
        sync: false
      - key: VK_APP_SECRET
        sync: false
